services:
  # app:
  #   image: plag-check:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   networks:
  #     - mynetwork
  #   environment:
  #     - REDIS_URL=redis://localhost:6379
  #     - REDIS_PORT=6379
  #   restart: always

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  redis_data:
