services:
  # app:
  #   image: plag-check:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   networks:
  #     - mynetwork
  #   environment:
  #     - REDIS_URL=redis://localhost:6379
  #     - REDIS_PORT=6379
  #   restart: always

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  zookeeper:
      image: zookeeper:latest
      restart: always
      ports:
        - "2181:2181"
      networks:
        - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - kafka-network


networks:
  mynetwork:
    driver: bridge
  kafka-network:
    driver: bridge

volumes:
  redis_data:
